name: Deploy Node.js App to EC2

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x] # You can update to the latest version if needed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            # Ensure the app directory exists
            mkdir -p /home/ubuntu/app
            cd /home/ubuntu/app
            
            # Clone repo if not already cloned
            if [ ! -d ".git" ]; then
              git clone https://github.com/Holuphilix/Github-Actions-Node.git .
            else
              git pull origin main
            fi

            # Set correct permissions
            sudo chown -R ubuntu:ubuntu /home/ubuntu/app

            # Install dependencies
            npm install

            # Restart application using PM2
            pm2 restart app || pm2 start index.js --name app
          EOF
